# action.yml
name: 'Container Image Updater'
description: 'Github action to notify if the container image needs update based on the baseimage change'
inputs:
  base-image:
    description: "Container Base image"
    required: true
  image:
    description: "Container image"
    required: true
  registry-username:
    description: "Container registry username"
    required: false
  registry-password:
    description: "Container registry password"
    required: false
outputs:
  needs-update:
    description: 'Needs the update or not(true or false)'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base-image }}
    - ${{ inputs.image }}
    - ${{ inputs.registry-username }}
    - ${{ inputs.registry-password }}
